// ÁREA DE TESTE DA CLASSE ROUND
//
// ESTE ARQUIVO SERÁ UTILIZADO PARA TESTAR:
// - CRIAÇÃO DE UM ROUND;
// - DEFINIÇÃO DOS TIMES ATACANTE E DEFENSOR;
// - RESULTADO DO ROUND;
// - FUNCIONAMENTO DA LÓGICA DE SIMULAÇÃO.

const Round = require("./rounds");